### ISSUE TITLE
一直不停检测，coin脚本反复执行

### ISSUE THREAD

**Issue by chaizia** [fishingworld/something#7]
![F1F4CC20-049C-4B61-82F8-D91B82EF3EB6](https://user-images.githubusercontent.com/10363691/142342444-b3b5c0bd-1760-4d03-9665-6f3bed8b8ad7.png)
![2689871F-C626-447E-B195-DE0A5CEFAD85](https://user-images.githubusercontent.com/10363691/142342455-48441839-d259-4089-aca4-3e9f5137735f.png)
![4F521B46-58DF-4B9B-96D2-C1439AB70013](https://user-images.githubusercontent.com/10363691/142342465-a7c6f349-94e4-4e98-8e15-0be58cc8c469.png)
我设置的coin频率是每天十点一次

`NetflixController = type=generic, script-path=https://raw.githubusercontent.com/fishingworld/something/main/NetflixSelect/netflixcontroller.js, timeout=3600, argument=icon1=checkmark.circle&color1=55ba94&icon2=checkmark.circle.trianglebadge.exclamationmark&color2=#9a9ced&icon3=hand.raised.circle&color3=#ea5532&netflixGroup=📺奈飞专线
NetflixChecker = type=cron,cronexp=* 10 * * *,wake-system=0,timeout=3600,script-path=https://raw.githubusercontent.com/fishingworld/something/main/NetflixSelect/netflixchecker.js,script-update-interval=86400,control-api=1
`

**Comment by fishingworld** [comment]
通知是捷径运行的通知，那个脚本的cron不要改

**Comment by chaizia** [comment]
感谢大佬解答
